server:
  port: 8088
  servlet:
    context-path: /demo
logging:
  level:
    root: info
    com.albert.auth.mapper: debug
    com.albert.common.security: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    local-cache-scope: statement