server:
  port: 8088
  servlet:
    context-path: /demo
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
logging:
  level:
    root: info
    com.albert.auth.mapper: debug
    com.albert.common.security: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml