spring:
  application:
    name: demo
  profiles:
    active: dev
    group:
      dev:
        - "dev"
        - "dev-db"
swagger:
  token:
    header: "Authorization"
security:
  token:
    header: "Authorization"
    username: "username"
    password: "password"